.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "PGIT" "1" "December 2014" "" ""
.
.SH "NAME"
\fBpgit\fR \- optimize your Pivotal Tracker and Git workflow
.
.SH "SYNOPSIS"
\fBpgit\fR
.
.SH "DESCRIPTION"
\fBpgit\fR is a simple command\-line tool that improves developer workflow\.
.
.SH "FILES"
.
.SH "EXAMPLES"

